local wezterm = require 'wezterm'
local home = os.getenv("HOME")
return {
    hide_tab_bar_if_only_one_tab = true,
    -- color_scheme = 'One Half Black (Gogh)',
    -- color_scheme = 'tokyonight',
    -- color_scheme = 'Ubuntu',
    -- color_scheme = 'Roya',
    color_scheme = 'Dracula+',
    font = wezterm.font('JetBrainsMono Nerd Font', {weight = 'Bold'}),
    -- font = wezterm.font('FantasqueSansMNerdFontMono', {weight = 'Bold'}),
    -- font = wezterm.font('Monaspace Radon Var', {weight = 1600}),
    -- font = wezterm.font("Monaspace Krypton Var", {weight=1600}),
    window_background_image_hsb = {
      attachment = "Scroll",
    },

    font_size = 10,
    colors = {
      cursor_fg = "black",
    },

    leader = { key = "e", mods = "CTRL" },
    check_for_updates = false,
    hide_mouse_cursor_when_typing = true,
    window_padding = {
      left = 0,
      right = 0,
      top = 0,
      bottom = 0,
    },

    keys = {
        { key = "o",   mods = "LEADER",       action = wezterm.action.ToggleFullScreen },
        { key = "`",   mods = "LEADER|CTRL",  action = wezterm.action { SendString = "`" } },
        { key = "V",   mods = "CTRL",         action = wezterm.action { PasteFrom = "Clipboard" } },
        { key = "\"",   mods = "LEADER|SHIFT",       action = wezterm.action { SplitVertical = { domain = "CurrentPaneDomain" } } },
        { key = "%",   mods = "LEADER|SHIFT",       action = wezterm.action { SplitHorizontal = { domain = "CurrentPaneDomain" } } },
        { key = "c",   mods = "LEADER",       action = wezterm.action { SpawnTab = "CurrentPaneDomain" } },
        { key = "h",   mods = "LEADER",       action = wezterm.action { ActivatePaneDirection = "Left" } },
        { key = "j",   mods = "LEADER",       action = wezterm.action { ActivatePaneDirection = "Up" } },
        { key = "k",   mods = "LEADER",       action = wezterm.action { ActivatePaneDirection = "Down" } },
        { key = "l",   mods = "LEADER",       action = wezterm.action { ActivatePaneDirection = "Right" } },
        { key = ",",   mods = "LEADER",       action = "ShowLauncher" },
        { key = "b",   mods = "LEADER",       action = "ShowTabNavigator" },
        { key = "f",   mods = "LEADER",       action = "QuickSelect" },
        { key = "\t",  mods = "LEADER",       action = "ActivateLastTab" },
        { key = "1",   mods = "LEADER",       action = wezterm.action { ActivateTab = 0 } },
        { key = "2",   mods = "LEADER",       action = wezterm.action { ActivateTab = 1 } },
        { key = "3",   mods = "LEADER",       action = wezterm.action { ActivateTab = 2 } },
        { key = "4",   mods = "LEADER",       action = wezterm.action { ActivateTab = 3 } },
        { key = "5",   mods = "LEADER",       action = wezterm.action { ActivateTab = 4 } },
        { key = "6",   mods = "LEADER",       action = wezterm.action { ActivateTab = 5 } },
        { key = "7",   mods = "LEADER",       action = wezterm.action { ActivateTab = 6 } },
        { key = "8",   mods = "LEADER",       action = wezterm.action { ActivateTab = 7 } },
        { key = "9",   mods = "LEADER",       action = wezterm.action { ActivateTab = 8 } },
        -- { key = "l", mods = "LEADER",       action=wezterm.action{EmitEvent="toggle-ligature"}},
        { key = "n",   mods = "LEADER",       action = wezterm.action { ActivateTabRelative = 1 } },
        { key = "p",   mods = "LEADER",       action = wezterm.action { ActivateTabRelative = -1 } },
        { key = "&",   mods = "LEADER|SHIFT", action = wezterm.action { CloseCurrentTab = { confirm = true } } },
        { key = "x",   mods = "LEADER",       action = wezterm.action { CloseCurrentPane = { confirm = true } } },
        { key = "w",   mods = "ALT",          action = wezterm.action({ CopyTo = "Clipboard" }) },
        { key = "y",   mods = "CTRL",         action = wezterm.action({ PasteFrom = "Clipboard" }) },
        { key = "Tab", mods = "LEADER",       action = wezterm.action({ ActivateTabRelative = 1 }) },
    },

}
